### DISCUSSION TITLE
The citations are not showing up

### DISCUSSION THREAD

**Discussion by Srihitha-l** [greenelab/lab-website-template#203] [Q&A] [answered]
In the _data folder I created a new file called sources-2019.yaml. I used sources.yaml as a template and filled in my citation information accordingly. But for some reason the citation won't show up.

**Comment by vincerubinetti** [comment]
Please link to the repo where you are experiencing problems. I won't be able to help you if I can't see more details about the problem.

**Reply by Srihitha-l** [reply]
According to this https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations, for a new citation to be created, I need to create a file that starts with sources and ends .yaml. Once I do that, citations.yaml https://github.com/greenelab/lab-website-template/blob/main/_data/citations.yaml should update on its own.
Sources.yaml https://github.com/greenelab/lab-website-template/blob/main/_data/sources.yaml was given in the template and I used that file to create a new file called sources-2019.yaml. But none of the citations that I create show up on the research page.

**Reply by vincerubinetti** [reply]
There are many reasons why that could happen. I cannot help you if you don't provide more information. Specifically, seeing the github actions workflow runs (I'm assuming you're not running anything locally), which I could find if you link me to your repo.

**Reply by Srihitha-l** [reply]
I am runnning everything locally, I don't have a github with my files.

**Reply by vincerubinetti** [reply]
Okay, are you running it via Docker or the more lengthy non-Docker method:
https://greene-lab.gitbook.io/lab-website-template-docs/getting-started/preview-your-site#on-your-computer-locally

Please paste any console log error messages that you are seeing.

Please zip and attach your folder to this discussion so I can see it.

**Reply by Srihitha-l** [reply]
I am using the non-Docker method, but it is a bit different than the one provided in the template. I just do bundle install and then bundle exec jekyll serve. I chose this method because I already had ruby and Jekyll installed on my mac.

**Reply by vincerubinetti** [reply, marked as answer]
Then that is why it is not updating. The auto-cite process is contained in the _cite/cite.py python script that needs to be run. The standard docker container runs this part for you. And if you're not using the docker approach, the docs right below it give you instructions on how to run it "manually" (e.g. when you already have ruby and jekyll installed) and include steps for running the auto-cite process. What you are doing is not part of the documentation. Also in the future, please provide **as much detail as possible** when you post a discussion.

**Reply by vincerubinetti** [reply]
You also have other issues. Here is your `sources-2019.yaml`:

```yaml
- id: .
  title: 'Bi-Directional Recurrent Neural Network Models for Geographic Location Extraction in Biomedical Literature'
  authors:
  - Arjun Magge
  - Davy Weissenbacher
  - Abeed Sarker
  - Matthew Scotch
  - Graciela Gonzalez-Hernandez
  type: paper
  date: 'January 2019'
  description: Magge A, Weissenbacher D, Sarker A, Scotch M, Gonzalez G. Bi-Directional Recurrent Neural Network Models for Geographic Location Extraction in Biomedical Literature. Proceedings of the Pacific Symposium on Biocomputing (PSB 2019). 2019; 100-111. Hawaii, USA.
  link: https://www.researchgate.net/publication/329240570_Bi-directional_Recurrent_Neural_Network_Models_for_Geographic_Location_Extraction_in_Biomedical_Literature
  
- id: doi:10.1007/s13181-019-00699-x
  title: Can Reddit Reveal Unique Facets of Suboxone Use and Misuse?
  authors:
  - Rachel Graves
  - Jeanmarie Perrone
  - Jennifer Love
  - Abeed Sarker
  description: R Graves, J Perrone, J Love, Abeed Sarker. Can Reddit Reveal Unique Facets of Suboxone Use and Misuse? Proceedings of the ACMT Annual Summit [meeting abstract]. 2019. San Francisco, USA. doi:10.1007/s13181-019-00699-x.
  date: 'March 2019'
  type: paper

# you're providing an id here, which makes Manubot generate the title, authors, publisher, date, and link, but then you're manually specifying the authors and date which overrides what Manubot generates automatically. are you sure you need to do this? you could remove title, authors, and date... unless you observe that the info Manubot is generating is not accurate in some way.

- id: doi:10.1007/s13181-019-00699-x
  title: Sentiment, Themes, and Analyses in Tweets about Suboxone
  authors:
  - Rachel Graves
  - Jeanmarie Perrone
  - Jennifer Love
  - Abeed Sarker
  description: J Love, J Perrone, R Graves, Abeed Sarker. Sentiment, Themes, and Analyses in Tweets about Suboxone. Proceedings of the ACMT Annual Summit [meeting abstract]. 2019; 58-59. San Francisco, USA. doi https://doi.org/10.1007/s13181-019-00699-x.
  date: 'March 2019'
  type: paper
```

You have two papers with the same id, so they will get [merged together](https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations#the-cite-process-in-detail...) and fields will get overwritten. You also have an `id: .`. If you [don't have an id for a paper and are filling its citation details in manually, just leave the `id` field absent](https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations#manual-override).

The dates you've put it are also not the [expected format](https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations#manual-override) (YYYY-MM-DD), and may cause issues with how your citations are sorted by date and how the date is displayed.
