### DISCUSSION TITLE
Book chapter citations not displaying correctly

### DISCUSSION THREAD

**Discussion by aaronjnewman** [greenelab/lab-website-template#205] [Q&A] [answered]
One of my ORCID citations is a chapter in an edited book. On my lab website, the citation appears for the book, not the chapter — ie the title shows as the book title, not the chapter title, and the "authors" show the editors of the book, not the chapter author (me). I suspect this is because there is a DOI for the book, but not individual DOIs for each chapter. However, if there is a way to override the default behavior in sources.yaml that would be great - I'm just not clear how from the documentation (book chapters don't seem to be covered in the docs). I realize I can just override the title and author, but that won't represent the fact that it's a chapter in a book. Ideally the chapter and book titles would render, along with both chapter author and editors.

For reference, my website is https://github.com/NeuroCognitiveImagingLab/NCIL-website-23
my ORCID is: https://orcid.org/my-orcid?orcid=0000-0001-5290-8342

The reference in question is from 2014 - book title is _Research Methods in Second Language Psycholinguistics_ 

thanks in advance
Aaron

**Comment by vincerubinetti** [comment, marked as answer]
As you mentioned, since there is no DOI or other ID for the individual chapter, there is nothing for the template/Manubot to really cite.

I think what you'll want to do is just [fill out the citation details for the chapter manually](https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations#manual-override). This means just putting all the details in a `sources.yaml` entry yourself, but without an id:

```yaml
- title: Research Methods in Second Language Psycholinguistics | Chapter 12
  authors:
    - Me
  publisher: Some Publisher
  date: "2023-01-01"
  link: https://doi.org/some-link
```

You might even want to give "chapter" it's own `type` to make it stand out with an icon:

```yaml
- title: blah
  type: chapter
```

Then in `types.yaml`:
```yaml
chapter:
  icon: fa-solid fa-bookmark
  # or anything else from https://fontawesome.com/search?o=r&m=free
```
