### DISCUSSION TITLE
Remove subtitle from header in mobile

### DISCUSSION THREAD

**Discussion by snaqvi1990** [greenelab/lab-website-template#237] [Q&A] [answered]
Last question I promise! I added a subtitle which looks great, but on mobile it makes the header on any of the non-main pages a little thick. Is there any way to remove the subtitle from these pages (but not the home page on mobile)?

 
![image](https://github.com/greenelab/lab-website-template/assets/7546459/8abbe099-5847-4654-9272-5d980dab2991)

**Comment by vincerubinetti** [comment, marked as answer]
Yes, in `/_styles/header.scss`, find this code already there:

```scss
// the header, when not "big" (on the homepage)
header:not([data-big]) {
   // when on a small screen width (mobile)
  @media (max-width: $collapse) {

    // add this (selects and hides the subtitle)
    .title > *:last-child {
      display: none;
    }
  }
}
```

I haven't tested this, but it should work.
