### DISCUSSION TITLE
Trying to add PMID and PMCID to citations

### DISCUSSION THREAD

**Discussion by andrewsu** [greenelab/lab-website-template#262] [General] [answered]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/SuLab/sulab.org/tree/pmid_test

### Version of Lab Website Template you are using

1.2.1

### Description

In this commit, https://github.com/SuLab/sulab.org/commit/aaedd81e5eabfc5ecb235c1c7ccd914b25157ae3, I'm trying to add the PMID and PMCID to the citation template.  (Ignore the other commits on that branch -- those were meant to go to main.)

I successfully updated `_cite/util.py` to parse that info from manubot, and I confirmed that information shows up in the `citations.yaml` file.  Example here:

```
- id: doi:10.1101/2023.05.01.538993
  title: 'DrugMechDB: A Curated Database of Drug Mechanisms'
  authors:
  - Adriana Carolina Gonzalez-Cavazos
  - Anna Tanska
  - Michael D. Mayers
  - Denise Carvalho-Silva
  - Brindha Sridharan
  - Patrik A. Rewers
  - Umasri Sankarlal
  - Lakshmanan Jagannathan
  - Andrew I. Su
  publisher: Cold Spring Harbor Laboratory
  PMID: '37205439'
  PMCID: PMC10187194
  date: '2023-05-02'
  link: https://doi.org/gtrg2f
  orcid: 0000-0002-7792-0150
  mike-mayers-list: true
  plugin: sources.py
  file: sources.yaml
  image: https://www.biorxiv.org/content/biorxiv/early/2023/05/03/2023.05.01.538993/F1.large.jpg
  buttons:
  - type: pdf
    link: pdf/Gonzalez-Cavazos_2023.pdf
```

I _thought_ I could get that to show up based on a quick addition to `_includes/citation.html` (referencing `citation.PMID` and `citation.PMCID`):

```
      <div class="citation-details">
        <span class="citation-publisher">
          {{- citation.publisher | default: "[no publisher info]" -}}
        </span>
        &nbsp;·&nbsp;
        <span class="citation-date">
          {{- citation.date | default: "[no date info]" | date: "%d %b %Y" -}}
        </span>
        &nbsp;·&nbsp;
        <span class="citation-id">
          {{- citation.id | default: "[no id info]" -}}
        </span>
        &nbsp;·&nbsp;
        <span class="citation-pmid">
          {{- citation.PMID | default: "[no pmid info]" -}}
        </span>
        &nbsp;·&nbsp;
        <span class="citation-pmcid">
          {{- citation.PMCID | default: "[no pmcid info]" -}}
        </span>
      </div>
```

but clearly I'm missing something...

![image](https://github.com/greenelab/lab-website-template/assets/2635409/855fadad-b472-499b-9261-44bbd261eeb7)

If someone can get me pointed in the right direction, that'd be appreciated!
