### ISSUE TITLE
Yaml typo in first time setup workflow, mv command not found

### ISSUE THREAD

**Issue by jbisits** [greenelab/lab-website-template#181]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/Climate-Data-Dynamics/climate-data-dynamics-lab-website

### Version of Lab Website Template you are using

1.1.2

### Description

I think there is a typo in the `first-time-setup.yaml` file on line 62

```yaml
      - name: Rename files
        run: \
          mv .github/user_pull_request_template.md .github/pull_request_template.md
```

The action failed the first time I ran it but after changing `\` -> `|` the workflow ran.
