### ISSUE TITLE
highlight specific authors in bold

### ISSUE THREAD

**Issue by sterding** [greenelab/lab-website-template#217]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Version of Lab Website Template you are using

1.1.6

### Description

I am wondering if you could allow to highlight an authors with bold by e.g. adding a * prefix. 

```
- id: doi:10.1186/s13059-023-03077-7
  title: Performance of computational algorithms to deconvolve heterogeneous bulk
    ovarian tumor tissue depends on experimental factors
  authors:
  - *Ariel A. Hippen
  - Dalia K. Omran
  - Lukas M. Weber
  - Euihye Jung
  - Ronny Drapkin
  - Jennifer A. Doherty
  - Stephanie C. Hicks
  - *Casey S. Greene
  publisher: Genome Biology
  date: '2023-10-20'
  link: https://doi.org/gswt6v
  orcid: 0000-0001-8713-9213
  member: casey-greene
  plugin: sources.py
  file: sources.yaml
  image: https://user-images.githubusercontent.com/542643/211156536-a2179f50-9d88-4b80-bb01-6247941bbe4b.png
  buttons:
  - type: preprint
    link: https://doi.org/10.1101/2022.12.04.519045
```
