### ISSUE TITLE
Not all new roles can be displayed 

### ISSUE THREAD

**Issue by sterding** [greenelab/lab-website-template#219]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Description

HI, 

I added two new roles in the _data/types.yaml file as below

```
scientist:
  icon: fa-solid fa-code
  description: Research Scientist

engineer:
  icon: fa-solid fa-code
  description: Bioinformatics Engineer
```

and have a member anthony-cicalo.md as below

```
---
name: Anthony Cicalo IV
image: images/headshots/anthony.jpg
role: engineer
---

Anthony Cicalo IV received .... 
``` 

However, it does not show the description for Anthony (see screenshot below). 

Even more strange, I have another new member in the role of `scientist`, but his photo is not shown in the member page at all, even though I have created the md file for him. Please help. 

![image](https://github.com/greenelab/lab-website-template/assets/682270/2d196a5c-3da4-456f-a926-b8bab2bb2ffc)
