### ISSUE TITLE
Manual override of `date` doesn't work in citations

### ISSUE THREAD

**Issue by michaelpginn** [greenelab/lab-website-template#245]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/lecs-lab/lecs-lab.github.io

### Version of Lab Website Template you are using

1.2.0

### Description

I am trying to manually override the `date` field in my sources, as in

```yml
- id: doi:10.18653/v1/2023.genbench-1.7
  date: 2023-12-01
```

However, this does not seem to work, as the `citations.yaml` file contains
```yml
- id: doi:10.18653/v1/2023.genbench-1.7
  title: Robust Generalization Strategies for Morpheme Glossing in an Endangered Language
    Documentation Context
  authors:
  - Michael Ginn
  - Alexis Palmer
  publisher: Proceedings of the 1st GenBench Workshop on (Benchmarking) Generalisation
    in NLP
  date: ''
  link: https://doi.org/gtmsc3
  plugin: sources.py
  file: sources.yaml
```

Is there something else I have to do to get this override to work? The dates that are automatically pulled are not correct.
