### ISSUE TITLE
Use `created-date` instead of `last-modified-date` in `orcid.py`

### ISSUE THREAD

**Issue by andrewsu** [greenelab/lab-website-template#260]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/andrewsu/sulab.org

### Version of Lab Website Template you are using

1.2.1

### Description

Out of the 156 citations currently in the `citations.yaml`, all but three of the IDs use the `doi` prefix.  The ones that don't are: `pmc:PMC3782358`, `pmid:11606367`, and `pmid:11507037`. For all three of these, the dates retrieved are incorrect. Taking `pmid:11606367` as an example, https://pubmed.ncbi.nlm.nih.gov/11606367 and https://aacrjournals.org/cancerres/article/61/20/7388/508137/Molecular-Classification-of-Human-Carcinomas-by show that this was published in 2001, but the entry in `citations.yaml` says the publication date is in 2022:

```
- id: pmid:11606367
  title: Molecular classification of human carcinomas by use of gene expression signatures.
  authors:
  - A I Su
  - J B Welsh
  - L M Sapinoso
  - S G Kern
  - P Dimitrov
  - H Lapp
  - P G Schultz
  - S M Powell
  - C A Moskaluk
  - H F Frierson
  - G M Hampton
  publisher: Cancer research
  date: '2022-05-23'
  link: http://europepmc.org/abstract/med/11606367
  orcid: 0000-0002-9859-4104
  member: andrew-su
  plugin: orcid.py
  file: orcid.yaml
```

It looks like orcid.py is pulling that from my ORCID profile via the API.  Here is the relevant snippet:

```
<activities:group>
	<common:last-modified-date>2022-05-23T23:38:16.840Z</common:last-modified-date>
	<common:external-ids>
		<common:external-id>
			<common:external-id-type>pmid</common:external-id-type>
			<common:external-id-value>11606367</common:external-id-value>
			<common:external-id-normalized transient="true">11606367</common:external-id-normalized>
			<common:external-id-url/>
			<common:external-id-relationship>self</common:external-id-relationship>
		</common:external-id>
	</common:external-ids>
	<work:work-summary put-code="13492064" path="/0000-0002-9859-4104/work/13492064" visibility="public" display-index="0">
		<common:created-date>2014-08-28T23:46:45.243Z</common:created-date>
		<common:last-modified-date>2022-05-23T23:38:16.840Z</common:last-modified-date>
		<common:source>
			<common:source-client-id>
				<common:uri>https://orcid.org/client/0000-0002-9157-3431</common:uri>
				<common:path>0000-0002-9157-3431</common:path>
				<common:host>orcid.org</common:host>
			</common:source-client-id>
			<common:source-name>Europe PubMed Central</common:source-name>
			<common:assertion-origin-orcid>
				<common:uri>https://orcid.org/0000-0002-9859-4104</common:uri>
				<common:path>0000-0002-9859-4104</common:path>
				<common:host>orcid.org</common:host>
			</common:assertion-origin-orcid>
			<common:assertion-origin-name>Andrew I. Su</common:assertion-origin-name>
		</common:source>
		<work:title>
			<common:title>Molecular classification of human carcinomas by use of gene expression signatures.</common:title>
		</work:title>
		<common:external-ids>
			<common:external-id>
				<common:external-id-type>pmid</common:external-id-type>
				<common:external-id-value>11606367</common:external-id-value>
				<common:external-id-normalized transient="true">11606367</common:external-id-normalized>
				<common:external-id-url/>
				<common:external-id-relationship>self</common:external-id-relationship>
			</common:external-id>
		</common:external-ids>
		<common:url>http://europepmc.org/abstract/med/11606367</common:url>
		<work:type>journal-article</work:type>
		<common:publication-date>
			<common:year>2001</common:year>
			<common:month>10</common:month>
		</common:publication-date>
	</work:work-summary>
</activities:group>
```

And it looks like `orcid.py` is pulling from `last-modified-date` instead of `publication-date`, and that's the cause of the error in these particular cases.  

Since it's just three entries, I'll override the dates for these entries in my `sources.yaml`. But just making the issue so you can assess whether a broader change is warranted...

**Comment by vincerubinetti** [comment]
Related to #258 . From that response, you can see how awful the schema is. There's duplicate dates, and three distinct ones, in different formats:

```yaml
last-modified-date: 2022-05-23T23:38:16.840Z
created-date: 2014-08-28T23:46:45.243Z
last-modified-date: 2022-05-23T23:38:16.840Z
publication-date:
  year: 2001
  month: 10
```

No idea which I should really use. Again, I want to have someone from ORCID comment. 

I would argue that having last updated is a more appropriate date to show (especially for people who have a lot of preprints), and don't really want to jump the shark of showing multiple dates in the citation component, for now. So I'll say this is behaving as expected. However, I'll use this issue to track having the other duplicate dates as _fallbacks_ if `last-modified-date` is not present.
