### ISSUE TITLE
Add Bluesky to social media

### ISSUE THREAD

**Issue by Llannelongue** [greenelab/lab-website-template#293]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

N/A

### Version of Lab Website Template you are using

1.3.1

### Description

Hi, such a great resource! It would be great to have the option to add Bluesky alongside twitter, hopefully something like this would work:
```
bluesky:
  icon: fa-brands fa-bluesky
  text: Bluesky
  tooltip: Bluesky
  link: https://bsky.app/profile/$VALUE
```
