### ISSUE TITLE
Handle case where user builds citations locally more gracefully

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#30]
If a user builds citations locally, when they make a PR, github actions will also to build them, causing a conflict in the research-output file.

Handle this better. Perhaps don't let the action run if output has also been touched.

**Comment by vincerubinetti** [comment]
My first idea was to use the not operator in the workflow paths like this:

```yaml
on:
  push:
    branches:
      - main
    paths:
      - "_data/research.yml"
      - "!_data/research-output.yml"
  pull_request:
    paths:
      - "_data/research.yml"
      - "!_data/research-output.yml"
```

I'm not sure if this actually works as intended (the workflow runs if research was touched, as long as research-output was not also touched).

But then I realized we probably want to have the workflow run any time the input is touched, and overwrite the output always, even if it was also edited by the user. 

In [this GL.com commit](https://github.com/greenelab/greenelab.com/commit/9a87c6b5c92c2d1aae5e1b2556a2cb586cc80320), I put in the option to force push. After some testing, I'll also implement it here. Hopefully it should always overwrite the output, even if the user committed the output, and avoid [this error](https://github.com/greenelab/greenelab.com/runs/2042911600?check_suite_focus=true): 

```
error: Your local changes to the following files would be overwritten by checkout:
	_data/research-output.yml
Please commit your changes or stash them before you switch branches.
Aborting
```
