### ISSUE TITLE
Use `actionlint` to help lint GitHub Actions workflow files

### ISSUE THREAD

**Issue by d33bs** [greenelab/lab-website-template#322]
This project could take advantage of [`actionlint`](https://github.com/rhysd/actionlint) to help lint GitHub Actions workflow files and prevent errors or enhance the work. While `actionlint` doesn't have a GH action, it does have a `pre-commit` hook, and there is a `pre-commit` action which could be used to integrate a check like this into CI.

**Comment by vincerubinetti** [comment]
I think this is worthwhile since this project has a lot of gh-actions workflows, and we can (theoretically) add it to the already-existing `versioning.yaml` workflow to check template version updates. The latter is important because the template tries to minimize the number of files in the repo at almost any cost to reduce update merging difficulties.

According to [these docs](https://github.com/rhysd/actionlint/blob/v1.7.7/docs/usage.md#use-actionlint-on-github-actions), it should be as simple as adding this step:

```yaml
run: |
  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
  ./actionlint -color
shell: bash
```

That should download the actionlint binary, and run it with the default arguments, which automatically scans the repo for workflows and checks them all.
