### ISSUE TITLE
truncated titles and variation in citation format?

### ISSUE THREAD

**Issue by hyphaltip** [greenelab/lab-website-template#94]
I'm trying to get our research pubs in order, I notice that some have truncated titles when pulling from pubmed or by DOI. Is there any way to force those in - maybe I have to add something manually bit know no point in manually fixing the html file since it will be regenerated
https://lab.stajich.org/research/

Also - is there a way to chance the citation style to be LASTNAME INITIALS, ... and maybe include the doi or citation on the page for copy+paste?

**Comment by vincerubinetti** [comment]
I'm guessing you're talking about entries like this one:

![image](https://user-images.githubusercontent.com/8326331/130493622-1017c1cc-c3de-43ee-89e2-7ee4242be570.png)

The template uses [Manubot](https://manubot.org/) to generate citation details (including fetching the title of the paper), which itself uses a few other tools and resources. Unfortunately there are errors with specific papers sometimes.

Luckily, you can [override any arbitrary field](https://github.com/greenelab/lab-website-template/wiki/Automatic-Citations) that you want from the input file. In your case (the screenshot above), in your `sources.yaml` file, you'd do this:

```yaml
- id: pmid:34067070
  title: Transcriptional Analysis of Coccidioides immitis Mycelia and Spherules by RNA Sequencing
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8150946/bin/jof-07-00366-g001.jpg
  tags:
    - coccidioides
    - onygenales
    - RNA-seq
```
